HOSTS:
  centos-64-x64:
    roles:
      - master
    platform: el-5-x86_64
    box : hajee/centos-5.8-oracle11
    # box : centos-59-x64-vbox4210-nocm
    hypervisor : vagrant
CONFIG:
  vagrant_memsize: 3072
  log_level: verbose
  type: foss
